WITH MAXS AS
(SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR)

SELECT M.YEAR, (M.MAXSIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN MAXS M
    ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV